services:
  job:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${HOME}/secrets/kartograafr:/kartograafr/configuration/secrets
      - .:/kartograafr
    container_name: kartograafr
